[package]
name = "dsweb-core"
version = "0.0.2"
edition = "2021"

[dependencies]
dscom = {path = "../dscom"}
clap = { version = "4", features = ["derive"]}
rouille = "3.6.2"

scrap = "0.5"
enigo = "0.1.2"
flate2 = "1.0"
clipboard = "0.5"
